In [1]:
import pandas as pd

#pegando base de dados .csv
df = pd.read_csv('vendas_acai.csv')
df = df.dropna()

#mudando para data
df['data_venda'] = pd.to_datetime(df['data_venda'])
df['mensal'] = df['data_venda'].dt.month

#filtros
produto_mais_vendido = df.groupby('produto')['total_venda'].sum().sort_values(ascending=False).reset_index()
valores = df.groupby('produto')['total_venda'].sum().sort_values(ascending=False)
lucrativo = produto_mais_vendido.loc[0, 'produto']
top_5_produtos = produto_mais_vendido.head(5)
top_5_valores = valores.head(5)
mensal_vendas = df.groupby('mensal')['total_venda'].sum().sort_values(ascending=False).reset_index()
mmvr = mensal_vendas.head(5)

#test1
display(df)
print('O produto mais lucrativo é:', lucrativo)

#criando novo dicionario
relatorio = {
    'Produto mais Vendido': top_5_produtos['produto'].values.tolist(),
    'N. do Mês': mmvr['mensal'].values.tolist(),
    'Venda Total': top_5_produtos['total_venda'].values.tolist()
}
#transformando o dicionario para DataFrame
df2R = pd.DataFrame(relatorio)
#mudando o DataFrame para relatorio.csv
df2R.to_csv('Relatorio.csv', index=False)

,produto,quantidade,preco_unitario,data_venda,total_venda,mensal
0,Açaí Premium,7,20.0,2024-05-12,140.0,5
1,Açaí Vegano,1,15.0,2024-07-20,15.0,7
2,Açaí Tradicional,6,18.0,2024-12-13,108.0,12
3,Açaí com Granola,3,10.0,2024-01-21,30.0,1
4,Açaí com Nutella,7,20.0,2024-08-29,140.0,8
...,...,...,...,...,...,...
1195,Açaí com Leite Condensado,2,15.0,2024-12-04,30.0,12
1196,Açaí Vegano,5,12.0,2024-04-04,60.0,4
1197,Açaí Vegano,5,10.0,2024-06-29,50.0,6
1198,Açaí Tradicional,5,10.0,2024-10-14,50.0,10
1199,Açaí com Nutella,4,20.0,2024-11-17,80.0,11

O produto mais lucrativo é: Açaí com Nutella

In [2]:
import pandas as pd

dfff = pd.read_csv('Relatorio.csv')
display(dfff)

        Produto mais Vendido  N. do Mês  Venda Total
0           Açaí com Nutella          7      25114.0
1           Açaí com Granola          5      18040.0
2               Açaí Premium         12      16762.0
3           Açaí Tradicional          9      12201.0
4  Açaí com Leite Condensado         10      10070.0